[Bulk] Switch to Stripe Checkout.
mysociety/mapit.mysociety.org pull request #162
Opened 2024-10-09 15:50 UTC by dracos

As checkout lets you specify tax.

2024-10-29 13:40 UTC, davea requested changes

2024-10-29 13:40 UTC, davea commented on conf/general.yml-example
> +BULK_LOOKUK_PRICE_ID: 'price_123'
Small typo:
```suggestion
BULK_LOOKUP_PRICE_ID: 'price_123'
```

2024-10-29 13:40 UTC, davea commented on bulk_lookup/views.py
> +            'price': 'price_1Q7y4zLoAAr9vgdbwPHVezZ6',
Should this come from `settings.BULK_LOOKUP_PRICE_ID` rather than being hardcoded?

2024-10-29 15:54 UTC, dracos commented on bulk_lookup/views.py
> +            'price': 'price_1Q7y4zLoAAr9vgdbwPHVezZ6',
Would be good if I used the new config variable somewhere, wouldn't it, doh!

2024-10-29 19:40 UTC, davea approved these changes

2024-11-20 17:39 UTC, merged

2024-11-22 09:44 UTC, dracos commented on bulk_lookup/views.py
>              if self.object and self.object.plan.id == settings.PRICING[-1]['plan']:
As the looking up of self.object above in get_form_kwargs was removed, this was never true - added a similar is_authenticated/lookup of self.object here afterwards.