Move to timestamped deploy.
mysociety/mapit.mysociety.org pull request #37
Opened 2017-02-17 18:08 UTC by dracos

Set up a new virtualenv on each deploy (it will use cached wheels etc after the first time so it isn't bad), and make sure SSL warnings are dealt with.

This reduces any front-end downtime to only running `migrate`, everything else that used to be done while the site was down (check virtualenv, collectstatic, etc), is done whilst the site remains up. It'd be good if we could even skip migrate given we won't need to run it often, but this is still a big improvement.

2017-02-20 16:17 UTC, mhl requested changes
With a diff like this, where code which is substantially but not completely the same has been moved between files, it'll make it easier to read the history in the future if some of these changes are in separate commits before the code is moved. e.g. the dropping of support for virtualenvs before 1.7 is probably worth a commit message of its own, as is the new "Stop SSL warnings" line.

A couple of other things:
* Shouldn't `.venv` go into `.gitignore` now?
* Doesn't the virtualenv path in conf/httpd.conf-example need to be updated to `.venv` too?

2017-02-20 16:19 UTC, mhl commented
I meant to add - it's great that you're doing this! I've been wanting to do the same for Pombola for some time, and it'll be nice to have an example to copy :)

2017-02-20 16:33 UTC, mhl commented
Actually, I guess having `.venv` ignored isn't ideal either - one of those cases where git's missing an "ignored but precious" as well as "ignored but disposable" class of files. However, since nothing will ever have been committed at `.venv`, it's unlikely git will trash it in unless someone uses `git clean` or something...

2017-02-20 16:34 UTC, dracos commented
`.venv` is already in gitignore, always has been, so I thought I'd use it :)
Will tidy up the rest now, thanks.

2017-02-20 16:45 UTC, mhl commented
One other thing I just wanted to check - if STATIC_ROOT is still `../collected_static`, that should be fine when generating fingerprinted files, but if it's running with `DEBUG = True` (a staging site on firefly say?) it could clobber unfingerprinted files on a failed deploy. Maybe this isn't a big deal, but it might be easier to see that nothing bad's going to happen if you changed `STATIC_ROOT` to an ignored `static` directory within the repository, perhaps?

2017-02-20 16:59 UTC, mhl approved these changes

2017-02-20 17:09 UTC, merged

2017-04-09 18:58 UTC, dracos commented
Just to note an unforeseen behaviour of having `STATIC_ROOT` be "an ignored static directory within the repository" – as this recreates from scratch each time, new requests are of course fine but it does mean that e.g. a cached copy of the front page HTML does then try and load an image that no longer exists (because it's only present in an old static directory), we can see some examples of this in our web server logs for e.g. the hero image pre/post shrinking. It would be nice to leave old static files around for this situation, so perhaps it should switch to a shared static directory, I think that woud overall be nicer?

2017-04-10 11:19 UTC, mhl commented
I guess that'd be fine, how about the alternative of copying over the previous static directory before running `collectstatic`. With the shard static directory, even if `collectstatic` is the last command run in the pre-deploy, it can fail half-way through - when `DEBUG` is `False` that shouldn't be a problem, I guess, since the files should be fingerprinted, but it could be on dev or staging sites where you'd end up with some of the old files, some new.